### ISSUE TITLE
seekTo method update delay

### ISSUE THREAD

**Issue by Taewa** [arielfaur/cordovaMedia2#2]
First of all, thanks for nice plugin. Very useful for audio control.

What I want to do is simply 
1. provide an audio status bar that user can see how much time left 
2. and user can drag this status bar so he can listen to whichever he wants.

the problem is 2.

I am using `input range` html tag to make it
Whenever user drags `input range` it will be detected by angular (ng-change)
Then I use `seekTo` method to move `input range slider` on correct position.

The audio plays properly when I use `seekTo` method. 
However, the `input range slider` delays 1 second.

I attached a screen shot file.

Explain of this image : 

I assume the blue line is the problem.
`45.929` is log from `CDVSound.m` file's `getCurrentPositionAudio` method. (`jsString` variable)

And just under `sec : 9.595893234` comes from `cordovaMedia2.js` file's `setTimer` method. (`media.getCurrentPosition`'s success callback's `position` variable)

The blue line is the moment when I use `seekTo` method.
`getCurrentPositionAudio` method gets correctly but `setTimer` method gets wrong info for 1second. 

Anybody knows how to resolve this problem?

Thank you.

![seekto](https://cloud.githubusercontent.com/assets/10694180/14525505/0ce33224-023e-11e6-9ced-f330242b9268.gif)

**Comment by arielfaur** [comment]
Hi @Taewa 
This project was just a test and it is not a plugin. You could try the ionic-audio plugin which already has a built in slider: https://github.com/arielfaur/ionic-audio

**Comment by Taewa** [comment]
Hi @arielfaur 
Thanks for your recommendation.
